{
 "title": "Mojaloop - Central-Ledger",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Central Ledger Lag by Consumer Group",
   "type": "graph",
   "description": "Central Ledger Lag by Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"cl-group-.*\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Central-Service - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_cl_prep_hand_transfer_prepare_count{}[30s])) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(rate(moja_cl_posi_hand_transfer_position_count{}[30s])) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(rate(moja_cl_fulf_hand_transfer_fulfil_count{}[30s])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Transfer Positions / sec",
   "type": "singlestat",
   "description": "Transfer Positions / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_cl_posi_hand_transfer_position_count{}[30s]))"
    }
   ]
  },
  {
   "title": "Transfers Prepares / sec",
   "type": "singlestat",
   "description": "Transfers Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_cl_prep_hand_transfer_prepare_count{}[30s]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfers Fullfills / sec",
   "type": "singlestat",
   "description": "Transfers Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_cl_fulf_hand_transfer_fulfil_count{}[30s]))"
    }
   ]
  },
  {
   "title": "Central-Service - Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(moja_cl_prep_hand_transfer_prepare_sum[30s]) / irate(moja_cl_prep_hand_transfer_prepare_count[30s])",
     "legendFormat": "Transfer Prepare - {{fspId}}"
    },
    {
     "expr": "irate(moja_cl_posi_hand_transfer_position_sum[30s]) / irate(moja_cl_posi_hand_transfer_position_count[30s])",
     "legendFormat": "Transfer Position - {{fspId}}"
    },
    {
     "expr": "avg(irate(moja_cl_prep_hand_transfer_prepare_sum[30s]) / irate(moja_cl_prep_hand_transfer_prepare_count[30s]))",
     "legendFormat": "Transfer Prepare - Average"
    },
    {
     "expr": "avg(irate(moja_cl_posi_hand_transfer_position_sum[30s]) / irate(moja_cl_posi_hand_transfer_position_count[30s]))",
     "legendFormat": "Transfer Position - Average"
    },
    {
     "expr": "avg(irate(moja_cl_fulf_hand_transfer_fulfil_sum[30s]) / irate(moja_cl_fulf_hand_transfer_fulfil_count[30s]))",
     "legendFormat": "Transfer Fulfil - Average"
    }
   ]
  },
  { "title": "CPU Usage by App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Central Services Total CPU Usage",
   "type": "singlestat",
   "description": "Central Services Total CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-centralledger-hand.*|test-centralledger-serv.*|test-centralledger-handler-transfer-fulfil.*'}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100",
     "legendFormat": "Central Services Total CPU Usage"
    }
   ]
  },
  {
   "title": "Transfer Prepare Handler CPU Usage",
   "type": "singlestat",
   "description": "Transfer Prepare Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-centralledger-hand-tr-prepare.*'}[30s])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100",
     "legendFormat": "Transfer Prepare Handler CPU Usage"
    }
   ]
  },
  {
   "title": "Transfer Position Handler CPU Usage",
   "type": "singlestat",
   "description": "Transfer Position Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-centralledger-hand-tr-position.*'}[30s])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100",
     "legendFormat": "Transfer Position Handler CPU Usage"
    }
   ]
  },
  {
   "title": "Transfer Fulfil Handler CPU Usage",
   "type": "singlestat",
   "description": "Transfer Fulfil Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-centralledger-handler-transfer-fulfil.*'}[30s])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100",
     "legendFormat": "Transfer Fulfil Handler CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Central-Service  - CPU Usage in Seconds by Pod",
     "type": "graph",
     "description": "Central-Service  - CPU Usage in Seconds by Pod",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (irate (moja_cl_prep_hand_process_cpu_seconds_total[1m])) by (app) ",
       "legendFormat": "{{app}}"
      },
      {
       "expr": "sum (irate (moja_cl_posi_hand_process_cpu_seconds_total[1m])) by (app)",
       "legendFormat": "{{app}}"
      },
      {
       "expr": "sum (irate (moja_cl_fulf_hand_process_cpu_seconds_total[1m])) by (app)",
       "legendFormat": "{{app}}"
      },
      {
       "expr": "sum(\n    irate(container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-centralledger-hand.*|test-centralledger-serv.*|test-centralledger-handler-transfer-fulfil.*'}[30s]))\nby (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Central-Service  - Event Loop Lag in Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_cl_prep_hand_nodejs_eventloop_lag_seconds)",
     "legendFormat": "Transfer Prepare"
    },
    {
     "expr": "avg(moja_cl_posi_hand_nodejs_eventloop_lag_seconds)",
     "legendFormat": "Transfer Position"
    },
    {
     "expr": "avg(moja_cl_fulf_hand_nodejs_eventloop_lag_seconds)",
     "legendFormat": "Transfer Fulfil"
    }
   ]
  },
  {
   "title": "Central-Service - # Pods for each Components",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-centralledger-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}