{
 "title": "Mojaloop - Simulators",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Simulator - Processed per sec",
   "type": "graph",
   "description": "Simulator - Processed per sec",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moja_sim_http_request_count[30s])) by (fsp, operation)",
     "legendFormat": "{{fsp}} - {{operation}}"
    },
    {
     "expr": "sum(irate(moja_sim_http_request_count[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(moja_sim_http_request_count[30s])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "postTransfer / sec for Payee",
   "type": "singlestat",
   "description": "postTransfer / sec for Payee",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_sim_http_request_count{fsp='payee', operation='postTransfers'}[30s]))"
    }
   ]
  },
  {
   "title": "putTransfersById / sec for Payee",
   "type": "singlestat",
   "description": "putTransfersById / sec for Payee",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(moja_sim_http_request_count{fsp='payee', operation='putTransfersById'}[30s]))"
    }
   ]
  },
  {
   "title": "messages / second",
   "type": "singlestat",
   "description": "messages / second",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(moja_sim_http_request_count{fsp='payee'}[30s]))"
    }
   ]
  },
  {
   "title": "Simulators - Processing Time",
   "type": "graph",
   "description": "Simulators - Processing Time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moja_sim_http_request_sum[30s]) / irate(moja_sim_http_request_count[30s])) by (fsp, operation, kubernetes_pod_name)",
     "legendFormat": "{{fsp}} - {{operation}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(irate(moja_sim_http_request_sum[30s]) / irate(moja_sim_http_request_count[30s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(irate(moja_sim_http_request_sum[30s]) / irate(moja_sim_http_request_count[30s])) by (fsp, operation)",
     "legendFormat": "{{fsp}} - {{operation}} - Average"
    },
    {
     "expr": "avg(irate(moja_sim_http_request_sum[30s]) / irate(moja_sim_http_request_count[30s])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Simulators - Event Loop Lag in Seconds",
   "type": "graph",
   "description": "Simulators - Event Loop Lag in Seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_sim_nodejs_eventloop_lag_seconds)"
    }
   ]
  },
  {
   "title": "Simulators - # Pods for each Components",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*simulators.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}