{
 "title": "Mojaloop - ML-API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ML API Lag by  Consumer Group",
   "type": "graph",
   "description": "ML API Lag by  Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"ml-group.*\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "ML-API - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_ml_service_transfers_prepare_count{}[30s])) by (app)",
     "legendFormat": "Transfers API Prepare"
    },
    {
     "expr": "sum(rate(moja_ml_service_transfers_fulfil_count{}[30s])) by (app)",
     "legendFormat": "Transfers API Fulfill"
    },
    {
     "expr": "sum(rate(moja_ml_notifi_hand_notification_event_count{}[30s])) by (app)",
     "legendFormat": "Notification Events"
    }
   ]
  },
  {
   "title": "Transfers API Prepares / sec",
   "type": "singlestat",
   "description": "Transfers API Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_ml_service_transfers_prepare_count{}[30s]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfers API Fullfills / sec",
   "type": "singlestat",
   "description": "Transfers API Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_ml_service_transfers_fulfil_count{}[30s]))"
    }
   ]
  },
  {
   "title": "Notification Events / Sec",
   "type": "singlestat",
   "description": "Notification Events / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(moja_ml_notifi_hand_notification_event_count{}[30s]))"
    }
   ]
  },
  {
   "title": "ML-API - Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moja_ml_service_transfers_prepare_sum[30s]) / irate(moja_ml_service_transfers_prepare_count[30s]))",
     "legendFormat": "Transfer API Prepare - Average"
    },
    {
     "expr": "avg(irate(moja_ml_service_transfers_fulfil_sum[30s]) / irate(moja_ml_service_transfers_fulfil_count[30s]))",
     "legendFormat": "Transfer API Fulfil - Average"
    },
    {
     "expr": "avg(irate(moja_ml_notifi_hand_notification_event_sum[30s]) / irate(moja_ml_notifi_hand_notification_event_count[30s]))",
     "legendFormat": "Notification Events - Average"
    }
   ]
  },
  { "title": "CPU Usage by App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Mojaloop API Adapter Total CPU Usage",
   "type": "singlestat",
   "description": "Mojaloop API Adapter Total CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-ml.*'}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100"
    }
   ]
  },
  {
   "title": "ML API Service CPU Usage",
   "type": "singlestat",
   "description": "ML API Service CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-ml-api-adapter-service-.*'}[30s])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100"
    }
   ]
  },
  {
   "title": "ML API Notification CPU Usage",
   "type": "singlestat",
   "description": "ML API Notification CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-ml-api-adapter-handler-notification-.*'}[30s])) / sum (machine_cpu_cores{kubernetes_io_hostname=~'k8s-phoenix-perf1-gc.*'}) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "ML-API  -  CPU Usage in Seconds by Pod",
     "type": "graph",
     "description": "ML-API  -  CPU Usage in Seconds by Pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(\n    rate(container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-ml.*'}[30s]))\nby (pod_name)",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "sum(\n    rate(container_cpu_usage_seconds_total{namespace='test', pod_name=~'test-ml.*'}[30s]))",
       "legendFormat": "All Total"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "ML-API - # Nodes for each Components",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-ml-api-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ML-API  - Event Loop Lag in Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_ml_service_nodejs_eventloop_lag_seconds)",
     "legendFormat": "ML-API-Service"
    },
    {
     "expr": " avg(moja_ml_notifi_hand_nodejs_eventloop_lag_seconds)",
     "legendFormat": "ML-API-Notification-Handler"
    }
   ]
  }
 ]
}