{
 "title": "PXC/Galera Graphs",
 "tags": [
  "Percona",
  "HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mysql_global_status_wsrep_local_state, instance)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mysql_galera_variables_info{instance=~\"$instance\"}, wsrep_cluster_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_galera_variables_info{wsrep_cluster_name =\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ready to Accept Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_ready{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Local State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_local_state{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Desync Mode",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_wsrep_desync{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_cluster_status{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "gcache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_galera_gcache_size_bytes{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "FC (normal traffic)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_flow_control_status{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Galera Replication Latency",
   "type": "graph",
   "description": "Shows figures for the replication latency on group communication. It measures latency from the time point when a message is sent out to the time point when a message is received. As replication is a group operation, this essentially gives you the slowest ACK and longest RTT in the cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Maximum\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Maximum\"}[5m])",
     "legendFormat": "{{ aggregator }}"
    },
    {
     "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Standard Deviation\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Standard Deviation\"}[5m])",
     "legendFormat": "{{ aggregator }}"
    },
    {
     "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Average\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Average\"}[5m])",
     "legendFormat": "{{ aggregator }}"
    },
    {
     "expr": "min_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Minimum\"}[$interval]) or\nmin_over_time(mysql_global_status_wsrep_evs_repl_latency{instance=\"$host\", aggregator=\"Minimum\"}[5m])",
     "legendFormat": "{{ aggregator }}"
    }
   ]
  },
  {
   "title": "Galera Replication Queues",
   "type": "graph",
   "description": "Shows the length of receive and send queues.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_wsrep_local_recv_queue{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_recv_queue{instance=\"$host\"}[5m])",
     "legendFormat": "Receive Queue"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_wsrep_local_send_queue{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_send_queue{instance=\"$host\"}[5m])",
     "legendFormat": "Send Queue"
    }
   ]
  },
  {
   "title": "Galera Cluster Size",
   "type": "graph",
   "description": "Shows the number of members currently connected to the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_wsrep_cluster_size{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cluster_size{instance=\"$host\"}[5m])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Galera Flow Control",
   "type": "graph",
   "description": "Shows the number of FC_PAUSE events sent/received. They are sent by a node when its replication queue gets too full. If a node is sending out FC messages it indicates a problem.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_flow_control_recv{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{instance=\"$host\"}[5m])",
     "legendFormat": "FC Messages Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_flow_control_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{instance=\"$host\"}[5m])",
     "legendFormat": "FC Messages Sent"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_wsrep_flow_control_paused_ns{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{instance=\"$host\"}[5m]))/1000000000",
     "legendFormat": "Paused due to Flow Control"
    }
   ]
  },
  {
   "title": "Galera Parallelization Efficiency",
   "type": "graph",
   "description": "Shows the average distances between highest and lowest seqno that are concurrently applied, committed and can be possibly applied in parallel (potential degree of parallelization).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_wsrep_apply_window{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_apply_window{instance=\"$host\"}[5m])",
     "legendFormat": "Apply Window"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_wsrep_commit_window{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_commit_window{instance=\"$host\"}[5m])",
     "legendFormat": "Commit Window"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_wsrep_cert_deps_distance{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cert_deps_distance{instance=\"$host\"}[5m])",
     "legendFormat": "Cert Deps Distance"
    }
   ]
  },
  {
   "title": "Galera Writing Conflicts",
   "type": "graph",
   "description": "Shows the number of local transactions being committed on this node that failed certification (some other node had a commit that conflicted with ours) – client received deadlock error on commit and also the number of local transactions in flight on this node that were aborted because they locked something an applier thread needed – deadlock error anywhere in an open transaction. Spikes in the graph may indicate writing to the same table potentially the same rows from 2 nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_local_cert_failures{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_local_cert_failures{instance=\"$host\"}[5m])",
     "legendFormat": "Local Cert Failures"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_local_bf_aborts{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_local_bf_aborts{instance=\"$host\"}[5m])",
     "legendFormat": "Local Bf Aborts"
    }
   ]
  },
  {
   "title": "Available Downtime before SST Required",
   "type": "graph",
   "description": "Shows for how long the node can be taken out of the cluster before SST is required. SST is a full state transfer method.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_galera_gcache_size_bytes{instance=\"$host\"}/(rate(mysql_global_status_wsrep_replicated_bytes{instance=\"$host\"}[5m])+rate(mysql_global_status_wsrep_received_bytes{instance=\"$host\"}[5m])) * 300",
     "legendFormat": "Time (5m avg)"
    }
   ]
  },
  {
   "title": "Galera Writeset Count",
   "type": "graph",
   "description": "Shows the count of transactions received from the cluster (any other node) and replicated to the cluster (from this node).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received{instance=\"$host\"}[5m])",
     "legendFormat": "Transactions Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_replicated{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated{instance=\"$host\"}[5m])",
     "legendFormat": "Transactions Replicated"
    }
   ]
  },
  {
   "title": "Galera Writeset Size",
   "type": "graph",
   "description": "Shows the average transaction size received/replicated.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_received_bytes{instance=\"$host\"}[$interval]) / rate(mysql_global_status_wsrep_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{instance=\"$host\"}[5m]) / irate(mysql_global_status_wsrep_received{instance=\"$host\"}[5m])",
     "legendFormat": "Incoming Transaction Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_replicated_bytes{instance=\"$host\"}[$interval]) / rate(mysql_global_status_wsrep_replicated{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{instance=\"$host\"}[5m]) / irate(mysql_global_status_wsrep_replicated{instance=\"$host\"}[5m])",
     "legendFormat": "Replicating Transaction Size"
    }
   ]
  },
  {
   "title": "Galera Writeset Traffic",
   "type": "graph",
   "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_received_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_wsrep_replicated_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Galera Network Usage Hourly",
   "type": "graph",
   "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_wsrep_received_bytes{instance=\"$host\"}[1h])",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_wsrep_replicated_bytes{instance=\"$host\"}[1h])",
     "legendFormat": "Replicated"
    }
   ]
  }
 ]
}