apiVersion: v2
version: 17.4.0
appVersion: ".13.0; .1.0"
description: A Helm chart containing Prometheus & Grafana for Kubernetes
name: promfana
type: application

maintainers:
  - name: Shashikant Hirugade
    email: shashi.mojaloop@gmail.com

dependencies:
  - name: kube-prometheus-stack
    alias: kps
    version: 87.13.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-kafka-exporter
    alias: kafka-exporter
    version: 3.1.0
    repository: https://prometheus-community.github.io/helm-charts
