apiVersion: v2
version: 17.2.0
appVersion: "kube-prometheus-stack: v82.14.0; prometheus-kafka-exporter: v3.0.1"
description: A Helm chart containing Prometheus & Grafana for Kubernetes
name: promfana
type: application

maintainers:
  - name: Shashikant Hirugade
    email: shashi.mojaloop@gmail.com

dependencies:
  - name: kube-prometheus-stack
    alias: kps
    version: 82.14.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-kafka-exporter
    alias: kafka-exporter
    version: 3.0.1
    repository: https://prometheus-community.github.io/helm-charts