apiVersion: v2
name: mojaloop-iam
description: Mojaloop IAM stack — Ory (Oathkeeper, Keto, Kratos, Hydra) and Mojaloop Ory IAM services
type: application
version: 17.2.0
appVersion: "0.1.0"
keywords:
  - mojaloop
  - iam
  - rbac
  - ory
  - hydra
sources:
  - https://github.com/mojaloop/helm
dependencies:
  - name: oathkeeper
    version: 0.61.1
    repository: "https://k8s.ory.sh/helm/charts"
    condition: oathkeeper.enabled
  - name: keto
    version: 0.61.1
    repository: "https://k8s.ory.sh/helm/charts"
    condition: keto.enabled
  - name: kratos
    version: 0.61.1
    repository: "https://k8s.ory.sh/helm/charts"
    condition: kratos.enabled
  - name: hydra
    version: 0.61.1
    repository: "https://k8s.ory.sh/helm/charts"
    condition: hydra.enabled
  - name: ml-iam-services
    version: 17.2.0
    repository: "file://../ml-iam-services"
