{
 "title": "Performance Troubleshooting",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Node information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance) /\nsum(irate(node_cpu_seconds_total[1m])) by (instance)\n* on(instance) group_left (nodename) node_uname_info{nodename=~\".+\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "RAM utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    1- (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)\n) * on(instance) group_left (nodename) node_uname_info{nodename=~\".+\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    1-(node_filesystem_avail_bytes{device=\"/dev/root\"}/node_filesystem_size_bytes{device=\"/dev/root\"})\n) * on(instance) group_left (nodename) node_uname_info{nodename=~\".+\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node list",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(node_uname_info{job=\"node-exporter\", nodename=~\".+(moja|kafka|sts).+\"}) by (nodename)",
     "legendFormat": "auto"
    }
   ]
  },
  { "title": "Container Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "ECONNRESET and Socket hang up ERRORs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (serviceName)({error=~\"Error: read ECONNRESET\"})",
     "legendFormat": "ECONNRESET - {{serviceName}}"
    },
    {
     "expr": "sum by (serviceName)({error=~\"Error: socket hang up\"})",
     "legendFormat": "Socker hang up - {{serviceName}}"
    }
   ]
  },
  {
   "title": "mojaloop container restarting in last 5m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (container)(increase(kube_pod_container_status_restarts_total{namespace=~\"mojaloop\",container=~\"account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|kafka\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Mojaloop sidecar restarting last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "sum by (container)(increase(kube_pod_container_status_restarts_total{namespace=~\"mojaloop\",container=~\"account-lookup-service-sidecar|account-lookup-service-admin-sidcar|centralledger-handler-admin-transfer-sidecar|centralledger-handler-timeout-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-get-sidecar|centralledger-handler-transfer-position-sidecar|centralledger-service-sidecar\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases restarting last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (container)(increase(kube_pod_container_status_restarts_total{container=\"mysql\",namespace=\"mojaloop-db\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka restarting last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "sum by (container)(increase(kube_pod_container_status_restarts_total{container=\"kafka\",namespace=\"mojaloop\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mojaloop containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"mojaloop\",container=~\"account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|handler-pos-batch|kafka\"}",
     "legendFormat": "{{container}}-{{id}}"
    }
   ]
  },
  {
   "title": "Mojaloop container cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"mojaloop\",container=~\"account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|kafka|handler-pos-batch\"}[5m])",
     "legendFormat": "{{container}} - {{id}}"
    }
   ]
  },
  {
   "title": "Mojaloop sidecar containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"mojaloop\",container=~\"account-lookup-service-sidecar|account-lookup-service-admin-sidcar|centralledger-handler-admin-transfer-sidecar|centralledger-handler-timeout-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-get-sidecar|centralledger-handler-transfer-position-sidecar|centralledger-service-sidecar\"}",
     "legendFormat": "{{container}}-{{id}}"
    }
   ]
  },
  {
   "title": "Mojaloop sidecar container cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"mojaloop\",container=~\"account-lookup-service-sidecar|account-lookup-service-admin-sidcar|centralledger-handler-admin-transfer-sidecar|centralledger-handler-timeout-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-get-sidecar|centralledger-handler-transfer-position-sidecar|centralledger-service-sidecar\"}[5m])",
     "legendFormat": "{{container}}-{{id}}"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (pod)(mysql_global_status_max_used_connections{namespace=\"mojaloop-db\"})",
     "legendFormat": "Max Use Connections {{pod}}"
    },
    {
     "expr": "sum by (pod)(mysql_global_variables_max_connections{namespace=\"mojaloop-db\"})",
     "legendFormat": "Max Connections {{pod}}"
    }
   ]
  }
 ]
}