{
 "title": "Mojaloop - ML-API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ML API Lag by  Consumer Group",
   "type": "graph",
   "description": "ML API Lag by  Consumer Group",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"ml-group.*\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "ML-API - Processed per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[120s])) by (app)",
     "legendFormat": "Transfers API Prepare"
    },
    {
     "expr": "sum(rate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[120s])) by (app)",
     "legendFormat": "Transfers API Fulfill"
    },
    {
     "expr": "sum(rate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[120s])) by (app)",
     "legendFormat": "Notification Events"
    },
    {
     "expr": "sum(rate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[120s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[120s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Transfers API Prepares / sec",
   "type": "singlestat",
   "description": "Transfers API Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[120s]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfers API Fullfills / sec",
   "type": "singlestat",
   "description": "Transfers API Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[120s]))"
    }
   ]
  },
  {
   "title": "Notification Events / Sec",
   "type": "singlestat",
   "description": "Notification Events / Sec",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[120s]))"
    }
   ]
  },
  {
   "title": "ML-API - Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moja_transfer_prepare_sum{serviceName=\"ml-service\"}[120s]) / irate(moja_transfer_prepare_count{serviceName=\"ml-service\"}[120s]))",
     "legendFormat": "Transfer API Prepare - Average"
    },
    {
     "expr": "avg(irate(moja_transfer_fulfil_sum{serviceName=\"ml-service\"}[120s]) / irate(moja_transfer_fulfil_count{serviceName=\"ml-service\"}[120s]))",
     "legendFormat": "Transfer API Fulfil - Average"
    },
    {
     "expr": "avg(irate(moja_notification_event_sum{serviceName=\"ml-handler-notification\"}[120s]) / irate(moja_notification_event_count{serviceName=\"ml-handler-notification\"}[120s]))",
     "legendFormat": "Notification Events - Average"
    }
   ]
  },
  { "title": "CPU Usage by App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Mojaloop API Adapter Total CPU Usage",
   "type": "singlestat",
   "description": "Mojaloop API Adapter Total CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api.*'}[2m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  {
   "title": "ML API Service CPU Usage",
   "type": "singlestat",
   "description": "ML API Service CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api-adapter-service.*'}[2m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  {
   "title": "ML API Notification CPU Usage",
   "type": "singlestat",
   "description": "ML API Notification CPU Usage",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*ml-api-adapter-handler-notification.*'}[2m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  { "title": "CPU Usage by Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "ML-API  -  CPU Usage in Seconds by Pod",
   "type": "graph",
   "description": "ML-API  -  CPU Usage in Seconds by Pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (moja_process_cpu_seconds_total{serviceName=~\"ml-.*\"}[2m])) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~'.*ml.*'}[2m]))",
     "legendFormat": "All Total"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "ML-API - # Nodes for each Components",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*ml-api-.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ML-API  - Event Loop Lag in Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_nodejs_eventloop_lag_seconds{serviceName=~\"ml.*\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}