{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prefix", "label": "metric prefix", "query": "moja_cl,moja_ml,moja_als,cbs" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(${prefix}_nodejs_version_info,instance)"
    }
   },
   {
    "name": "serviceName",
    "label": "serviceName",
    "query": {
     "query": "label_values(${prefix}_nodejs_version_info,serviceName)"
    }
   },
   {
    "name": "podName",
    "label": "podName",
    "query": {
     "query": "label_values(${prefix}_nodejs_version_info,kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(${prefix}_process_resident_memory_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, kubernetes_pod_name, serviceName) ",
     "legendFormat": "Process Memory - {{instance}} {{serviceName}}  {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(${prefix}_nodejs_heap_size_total_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, kubernetes_pod_name, serviceName) ",
     "legendFormat": "Heap Total - {{instance}} {{serviceName}}  {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(${prefix}_nodejs_heap_size_used_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, kubernetes_pod_name, serviceName) ",
     "legendFormat": "Heap Used - {{instance}} {{serviceName}}  {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(${prefix}_nodejs_external_memory_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, kubernetes_pod_name, serviceName) ",
     "legendFormat": "External Memory - {{instance}} {{serviceName}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(${prefix}_process_cpu_user_seconds_total{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}[$__rate_interval]) * 100) by (instance, kubernetes_pod_name, serviceName) ",
     "legendFormat": "User CPU - {{instance}} {{serviceName}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${prefix}_nodejs_active_handles_total{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, serviceName, kubernetes_pod_name)",
     "legendFormat": "Active Handler - {{instance}} {{serviceName}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(${prefix}_nodejs_active_requests_total{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, serviceName, kubernetes_pod_name)",
     "legendFormat": "Active Request - {{instance}} {{serviceName}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(${prefix}_nodejs_eventloop_lag_seconds{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, serviceName, kubernetes_pod_name)",
     "legendFormat": "{{instance}} {{serviceName}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(${prefix}_nodejs_heap_space_size_used_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, serviceName, kubernetes_pod_name, space)",
     "legendFormat": "Heap Used - {{instance}} {{serviceName}}  {{kubernetes_pod_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(${prefix}_nodejs_heap_space_size_total_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, serviceName, kubernetes_pod_name, space)",
     "legendFormat": "Heap Total - {{instance}} {{serviceName}} {{kubernetes_pod_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(${prefix}_nodejs_heap_space_size_available_bytes{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, serviceName, kubernetes_pod_name, space)",
     "legendFormat": "Heap Used - {{instance}} {{serviceName}}  {{kubernetes_pod_name}} - {{space}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(${prefix}_nodejs_version_info{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}) by (instance, kubernetes_pod_name, serviceName, version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(${prefix}_process_start_time_seconds{instance=~\"$instance\",kubernetes_pod_name=~\"$podName\", serviceName=~\"$serviceName\"}[$__rate_interval])) by (instance, serviceName, kubernetes_pod_name)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}