{
 "title": "Mojaloop - Simulators",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Simulator - Processed per sec",
   "type": "graph",
   "description": "Simulator - Processed per sec",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moja_sim_request_count[120s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(irate(moja_sim_request_count[120s])) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(rate(moja_sim_request_count[120s])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "postTransfer / sec for Payee",
   "type": "stat",
   "description": "postTransfer / sec for Payee",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_sim_request_count{operation='postTransfers'}[120s]))"
    }
   ]
  },
  {
   "title": "putTransfersById / sec for Payee",
   "type": "stat",
   "description": "putTransfersById / sec for Payee",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_sim_request_count{operation=\"putTransfersById\"}[120s]))"
    }
   ]
  },
  {
   "title": "messages / second",
   "type": "stat",
   "description": "messages / second",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(moja_sim_request_count[120s]))"
    }
   ]
  },
  {
   "title": "Simulators - Processing Time",
   "type": "graph",
   "description": "Simulators - Processing Time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moja_sim_request_sum[120s]) / irate(moja_sim_request_count[120s])) by (fsp, operation, kubernetes_pod_name)",
     "legendFormat": "{{fsp}} - {{operation}} - {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(irate(moja_sim_request_sum[120s]) / irate(moja_sim_request_count[120s])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(irate(moja_sim_request_sum[120s]) / irate(moja_sim_request_count[120s])) by (fsp, operation)",
     "legendFormat": "{{fsp}} - {{operation}} - Average"
    },
    {
     "expr": "avg(irate(moja_sim_request_sum[120s]) / irate(moja_sim_request_count[120s])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Simulators - Event Loop Lag in Seconds",
   "type": "graph",
   "description": "Simulators - Event Loop Lag in Seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(moja_nodejs_eventloop_lag_seconds{serviceName=\"simulator\"})"
    }
   ]
  },
  {
   "title": "Simulators - # Pods for each Components",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*simulator.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}