apiVersion: v2
appVersion: "3.0.2"
description: Connection Manager Helm chart for Kubernetes
name: connection-manager
version: 17.2.0
keywords:
  - connection-manager
sources:
  - https://github.com/pm4ml/connection-manager-api
  - https://github.com/pm4ml/connection-manager-ui
maintainers:
  - name: Ramiro González Maciel
    email: ramiro@modusbox.com
  - name: Ivan Annovazzi
    email: ivan.annovazzi@modusbox.com
