{
 "title": "Mojaloop - ALS",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Critical Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "app_critical_total{service=~\".*account-lookup-service.*\"}",
     "legendFormat": "{{service}} {{exported_service}}"
    }
   ]
  },
  { "title": "Party Resource Metric Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ing GET /parties/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_getPartiesByTypeAndID_count[$__range])) or vector(0)) + (sum(increase(moja_ing_getPartiesByTypeIDAndSubID_count[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Ing PUT /parties/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_putPartiesByTypeAndID_count[$__range])) or vector(0)) + (sum(increase(moja_ing_putPartiesByTypeIDAndSubID_count[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Ing PUT /parties/*/error requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_putPartiesErrorByTypeAndID_count[$__range])) or vector(0)) + (sum(increase(moja_ing_putPartiesErrorByTypeIDAndSubID_count[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "GET /parties/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(moja_getPartiesByTypeAndID_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_getPartiesByTypeAndID_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /parties/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(moja_putPartiesByTypeAndID_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_putPartiesByTypeAndID_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /parties/*/error Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(moja_puttPartiesErrorByTypeAndID_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_puttPartiesErrorByTypeAndID_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Party Resource Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Party Handlers Ingress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_ing_getPartiesByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_getPartiesByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putPartiesByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_putPartiesByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_getPartiesByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_getPartiesByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putPartiesByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_putPartiesByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putPartiesErrorByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_putPartiesErrorByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putPartiesErrorByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_putPartiesErrorByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Party Handler Ingress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_ing_getPartiesByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putPartiesByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_getPartiesByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "getPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putPartiesByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putPartiesErrorByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": " putPartiesErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putPartiesErrorByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Party Domain - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_getPartiesByTypeAndID_sum[$__rate_interval]) / rate(moja_getPartiesByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_putPartiesByTypeAndID_sum[$__rate_interval])  / rate(moja_putPartiesByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_puttPartiesErrorByTypeAndID_sum[$__rate_interval])  / rate(moja_puttPartiesErrorByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "puttPartiesErrorByTypeAndID success:{{success}}"
    }
   ]
  },
  {
   "title": "Party Domain - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_getPartiesByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_putPartiesByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_puttPartiesErrorByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "puttPartiesErrorByTypeAndID success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Resource Metric Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Ing GET /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_getParticipantsByTypeAndID_count[$__range])) or vector(0)) + (sum(increase(moja_ing_getParticipantsByTypeIdAndSubID_count[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Ing POST /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_postParticipantsbyTypeAndID_count[$__range])) or vector(0)) + (sum(increase(moja_ing_postParticipantsByTypeIDAndSubID_count[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Ing POST /participants requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(moja_ing_postParticipantsBatch_count[$__range]))"
    }
   ]
  },
  {
   "title": "Ing DELETE /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_deleteParticipantsByTypeAndID_count[$__range])) or verctor(0)) + (sum(increase(moja_ing_deleteParticipantsByTypeIDAndSubID_count[$__range])) or verctor(0))"
    }
   ]
  },
  {
   "title": "Ing PUT /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_putParticipantsByTypeAndID_count[$__range])) or verctor(0)) + (sum(increase(moja_ing_putParticipantsByTypeIDAndSubID_count[$__range])) or verctor(0))"
    }
   ]
  },
  {
   "title": "Ing PUT /participants/*/error requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(increase(moja_ing_putParticipantsErrorByTypeAndID_count[$__range])) or verctor(0)) + (sum(increase(moja_ing_putParticipantsErrorByTypeIDAndSubID_count[$__range])) or verctor(0))"
    }
   ]
  },
  {
   "title": "GET /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(moja_getParticipantsByTypeAndID_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_getParticipantsByTypeAndID_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(moja_postParticipants_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_postParticipants_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST BATCH /participants Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(moja_postParticipantsBatch_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_postParticipantsBatch_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(moja_deleteParticipants_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_deleteParticipants_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(moja_putParticipantsByTypeAndID_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_putParticipantsByTypeAndID_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /participants/*/error Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(moja_putParticipantsErrorByTypeAndID_count{success=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(moja_putParticipantsErrorByTypeAndID_count{success=\"false\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Participant Resource Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Participant Handlers Ingress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_ing_getParticipantsByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_getParticipantsByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putParticipantsByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_putParticipantsByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_postParticipantsbyTypeAndID_sum[$__rate_interval]) / rate(moja_ing_postParticipantsbyTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipantsbyTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_deleteParticipantsByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_deleteParticipantsByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "deleteParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_getParticipantsByTypeIdAndSubID_sum[$__rate_interval]) / rate(moja_ing_getParticipantsByTypeIdAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getParticipantsByTypeIdAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putParticipantsByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_putParticipantsByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_postParticipantsByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_postParticipantsByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_deleteParticipantsByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_deleteParticipantsByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "deleteParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putParticipantsErrorByTypeAndID_sum[$__rate_interval]) / rate(moja_ing_putParticipantsErrorByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_ing_putParticipantsErrorByTypeIDAndSubID_sum[$__rate_interval]) / rate(moja_ing_putParticipantsErrorByTypeIDAndSubID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Handler Ingress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_ing_getParticipantsByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putParticipantsByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_postParticipantsbyTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "postParticipantsbyTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_deleteParticipantsByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "deleteParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_getParticipantsByTypeIdAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "getParticipantsByTypeIdAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putParticipantsByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_postParticipantsByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "postParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_deleteParticipantsByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "deleteParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putParticipantsErrorByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_ing_putParticipantsErrorByTypeIDAndSubID_count[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Domain - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_getParticipantsByTypeAndID_sum[$__rate_interval]) / rate(moja_getParticipantsByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_putParticipantsByTypeAndID_sum[$__rate_interval]) / rate(moja_putParticipantsByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_putParticipantsErrorByTypeAndID_sum[$__rate_interval]) / rate(moja_putParticipantsErrorByTypeAndID_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_postParticipants_sum[$__rate_interval]) / rate(moja_postParticipants_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipants success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_postParticipantsBatch_sum[$__rate_interval]) / rate(moja_postParticipantsBatch_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipantsBatch success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_deleteParticipants_sum[$__rate_interval]) / rate(moja_deleteParticipants_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "deleteParticipants success:{{success}}"
    }
   ]
  },
  {
   "title": "Participants Domain - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_getParticipantsByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_putParticipantsByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_putParticipantsErrorByTypeAndID_count[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_postParticipants_count[$__rate_interval])) by (success)",
     "legendFormat": "postParticipants success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_postParticipantsBatch_count[$__rate_interval])) by (success)",
     "legendFormat": "postParticipantsBatch success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_postParticipantsBatch_count[$__rate_interval])) by (success)",
     "legendFormat": "deleteParticipants success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Egress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_egress_getParticipantEndpoint_sum[$__rate_interval]) / rate(moja_egress_getParticipantEndpoint_count[$__rate_interval]) >=0) by (endpointType,success)",
     "legendFormat": "getParticipantEndpoint {{endpointType}} success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_egress_sendRequestToParticipant_sum[$__rate_interval]) / rate(moja_egress_sendRequestToParticipant_count[$__rate_interval]) >=0) by (endpointType,success)",
     "legendFormat": "sendRequestToParticipant {{endpointType}} success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_egress_validateParticipant_sum[$__rate_interval]) / rate(moja_egress_validateParticipant_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "validateParticipant success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Egress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_egress_getParticipantEndpoint_count[$__rate_interval])) by (success, endpointType)",
     "legendFormat": "getParticipantEndpoint {{endpointType}} success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_egress_sendRequestToParticipant_count[$__rate_interval])) by (success, endpointType)",
     "legendFormat": "sendRequestToParticipant {{endpointType}} success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_egress_validateParticipant_count[$__rate_interval])) by (success)",
     "legendFormat": "validateParticipant {{endpointType}} success:{{success}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "ALS Total CPU Usage",
   "type": "gauge",
   "description": "ALS Total CPU Usage",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod=~'.*account-lookup.*'}[2m])) * 100"
    }
   ]
  },
  { "title": "Resource Usage by Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "ALS - Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moja_nodejs_heap_size_total_bytes{serviceName=~\"account-lookup.*\"}",
     "legendFormat": "heap_total-{{instance}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_nodejs_heap_size_used_bytes{serviceName=~\"account-lookup.*\"}",
     "legendFormat": "heap_used-{{instance}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_nodejs_external_memory_bytes{serviceName=~\"account-lookup.*\"}",
     "legendFormat": "ext_memory-{{instance}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "ALS  -  CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "ALS  -  CPU Usage in Seconds by Pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_process_cpu_seconds_total{serviceName=~\"account-lookup.*\"}[30s]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "ALS - # Nodes for each Components",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*account-lookup.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ALS  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_nodejs_eventloop_lag_seconds{serviceName=~\"account-lookup.*\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}