{
 "title": "Mojaloop - Quoting Service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Critical Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "app_critical_total{service=~\".*quoting.*\"}",
     "legendFormat": "{{service}} {{exported_service}}"
    }
   ]
  },
  { "title": "Database Cache Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Models - Cache Hits (True vs False)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moja_database_get_cache_value_count[$__rate_interval])) by (queryName, hit) ",
     "legendFormat": "{{queryName}}-{{hit}}"
    }
   ]
  },
  { "title": "Quote Resource Metric Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Ing GET /quotes/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(moja_quotes_id_get_count[$__range]))"
    }
   ]
  },
  {
   "title": "Ing PUT /quotes/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(moja_quotes_id_put_count[$__range]))"
    }
   ]
  },
  {
   "title": "Ing PUT /quotes/*/error requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(moja_quotes_id_put_error_count[$__range]))"
    }
   ]
  },
  {
   "title": "Ing POST /quotes requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(moja_quotes_post_count[$__range]))"
    }
   ]
  },
  {
   "title": "Quote Resource Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Quote Handlers Ingress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_quotes_post_sum[$__rate_interval]) / rate(moja_quotes_post_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postQuotes success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_quotes_id_put_sum[$__rate_interval]) / rate(moja_quotes_id_put_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putQuotesByID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_quotes_id_get_sum[$__rate_interval]) / rate(moja_quotes_id_get_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getQuotesByID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_quotes_id_put_error_sum[$__rate_interval]) / rate(moja_quotes_id_put_error_count[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putQuotesByIDError success:{{success}}"
    }
   ]
  },
  {
   "title": "Quote Handler Ingress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_quotes_id_put_error_count[$__rate_interval])) by (success)",
     "legendFormat": "putQuotesIDError success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_quotes_id_get_count[$__rate_interval])) by (success)",
     "legendFormat": "getQuotesByID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_quotes_id_put_count[$__rate_interval])) by (success)",
     "legendFormat": "putQuotesByID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_quotes_post_count[$__rate_interval])) by (success)",
     "legendFormat": "postQuotes success:{{success}}"
    }
   ]
  },
  {
   "title": "Quote Model - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_model_quote_sum[$__rate_interval]) / rate(moja_model_quote_count[$__rate_interval]) >=0) by (success, queryName)",
     "legendFormat": "{{queryName}} success:{{success}}"
    }
   ]
  },
  {
   "title": "Quote Model - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_model_quote_count[$__rate_interval])) by (success, queryName)",
     "legendFormat": "{{queryName}} success:{{success}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "QS Total CPU Usage",
   "type": "gauge",
   "description": "QS Total CPU Usage",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate (container_cpu_usage_seconds_total{pod=~'.*quoting-service.*'}[2m]))"
    }
   ]
  },
  { "title": "Resource Usage by Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "QS - Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moja_nodejs_heap_size_total_bytes{serviceName=~\"quoting-service.*\"}",
     "legendFormat": "heap_total-{{instance}} {{pod}}"
    },
    {
     "expr": "moja_nodejs_heap_size_used_bytes{serviceName=~\"quoting-service.*\"}",
     "legendFormat": "heap_used-{{instance}} {{pod}}"
    },
    {
     "expr": "moja_nodejs_external_memory_bytes{serviceName=~\"quoting-service.*\"}",
     "legendFormat": "ext_memory-{{instance}} {{pod}}"
    }
   ]
  },
  {
   "title": "QS  -  CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "QS  -  CPU Usage in Seconds by Pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_process_cpu_seconds_total{serviceName=~\"quoting-service.*\"}[30s]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "QS - # Nodes for each Components",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*quoting-service.*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "QS  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_nodejs_eventloop_lag_seconds{serviceName=~\"quoting-service.*\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}