{
 "title": "Performance Troubleshooting",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", cluster=\"$cluster\"}[1m])) by (instance) /\nsum(irate(node_cpu_seconds_total{cluster=\"$cluster\"}[1m])) by (instance)\n* on(instance) group_left (nodename) node_uname_info{nodename=~\".+\", cluster=\"$cluster\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "RAM utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    1- (node_memory_MemAvailable_bytes{cluster=\"$cluster\"}/node_memory_MemTotal_bytes{cluster=\"$cluster\"})\n) * on(instance) group_left (nodename) node_uname_info{nodename=~\".+\", cluster=\"$cluster\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    1-(node_filesystem_avail_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\", cluster=\"$cluster\"}/node_filesystem_size_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\", cluster=\"$cluster\"})\n) * on(instance) group_left (nodename) node_uname_info{nodename=~\".+\", cluster=\"$cluster\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node list",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(node_uname_info{job=\"node-exporter\", nodename=~\".+(moja|kafka|sts).+\", cluster=\"$cluster\"}) by (nodename)",
     "legendFormat": "auto"
    }
   ]
  },
  {
   "title": "Offending processes - High node CPU utilisation ",
   "type": "timeseries",
   "description": "Shows processes which are consuming more than 70% of the node CPU.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\"}[1m])) by (groupname,nodename)\n    / on (nodename) group_left\n    sum(rate(node_cpu_seconds_total{cluster=\"$cluster\"}[1m])) by (nodename)\n) > 0.7",
     "legendFormat": "{{nodename}}:{{groupname}}"
    }
   ]
  },
  {
   "title": "Offending processes - High node memory utilisation ",
   "type": "timeseries",
   "description": "Shows processes which are consuming more than 70% of the node memory.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    namedprocess_namegroup_memory_bytes{memtype=\"resident\", cluster=\"$cluster\"} \n    / on (nodename) group_left\n    node_memory_MemTotal_bytes{cluster=\"$cluster\"}\n) > 0.7\n",
     "legendFormat": "{{nodename}}:{{groupname}}"
    }
   ]
  },
  {
   "title": "Network I/O - Download",
   "type": "timeseries",
   "description": "Shows network interfaces on each node which are consuming more than 1 MiB/s bandwidth (download).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"cali.*|lo\",cluster=\"$cluster\"}[1m])) by (nodename,instance,device) > 1024 * 1024",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Network I/O - Upload",
   "type": "timeseries",
   "description": "Shows network interfaces on each node which are consuming more than 1 MiB/s bandwidth (upload)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"cali.*|lo\",cluster=\"$cluster\"}[1m])) by (nodename,instance,device) > 1024 * 1024",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O - Read",
   "type": "timeseries",
   "description": "Shows disks  on each node which are consuming more than 1 MiB/s disk read bandwidth ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\"}[1m])) by (instance,nodename,device) > 1024 * 1024",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O - Write",
   "type": "timeseries",
   "description": "Shows disks  on each node which are consuming more than 1 MiB/s disk write bandwidth ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\"}[1m])) by (instance,nodename,device) > 1024 * 1024",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  { "title": "Container Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "ECONNRESET and Socket hang up ERRORs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (serviceName, container)({error=~\"Error: read ECONNRESET\", cluster=\"$cluster\"})",
     "legendFormat": "ECONNRESET - {{serviceName}} - {{container}}"
    },
    {
     "expr": "sum by (serviceName, container)({error=~\"Error: socket hang up\", cluster=\"$cluster\"})",
     "legendFormat": "Socker hang up - {{serviceName}} - {{container}}"
    }
   ]
  },
  {
   "title": "mojaloop container restarting in last 5m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (container)(increase(kube_pod_container_status_restarts_total{namespace=~\"mojaloop\",container=~\"account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|kafka\", cluster=\"$cluster\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Mojaloop sidecar restarting last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sum by (container)(increase(kube_pod_container_status_restarts_total{namespace=~\"mojaloop\",container=~\"account-lookup-service-sidecar|account-lookup-service-admin-sidcar|centralledger-handler-admin-transfer-sidecar|centralledger-handler-timeout-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-get-sidecar|centralledger-handler-transfer-position-sidecar|centralledger-service-sidecar\", cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases restarting last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (pod)(increase(kube_pod_container_status_restarts_total{container=\"mysql\",namespace=\"mojaloop-db\", cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka restarting last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "sum by (pod)(increase(kube_pod_container_status_restarts_total{container=\"kafka\",namespace=\"mojaloop\", cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mojaloop containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"mojaloop\",container=~\"account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|handler-pos-batch|kafka\", cluster=\"$cluster\"}",
     "legendFormat": "{{container}}-{{id}}"
    }
   ]
  },
  {
   "title": "Mojaloop container cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"mojaloop\",container=~\"account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|kafka|handler-pos-batch\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{container}} - {{id}}"
    }
   ]
  },
  {
   "title": "Mojaloop pods Network I/O - Download",
   "type": "timeseries",
   "description": "Shows mojaloop pods which are consuming more than 1 MiB/s network download bandwidth ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=~\"mojaloop\", pod=~\".*(account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|handler-pos-batch|kafka).*\", cluster=\"$cluster\"}[5m]) > 1024 * 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mojaloop pods Network I/O - Upload",
   "type": "timeseries",
   "description": "Shows mojaloop pods which are consuming more than 1 MiB/s network upload bandwidth ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=~\"mojaloop\", pod=~\".*(account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service|handler-pos-batch|kafka).*\", cluster=\"$cluster\"}[5m]) > 1024 * 1024 ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mojaloop sidecar containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"mojaloop\",container=~\"account-lookup-service-sidecar|account-lookup-service-admin-sidcar|centralledger-handler-admin-transfer-sidecar|centralledger-handler-timeout-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-get-sidecar|centralledger-handler-transfer-position-sidecar|centralledger-service-sidecar\", cluster=\"$cluster\"}",
     "legendFormat": "{{container}}-{{id}}"
    }
   ]
  },
  {
   "title": "Mojaloop sidecar container cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"mojaloop\",container=~\"account-lookup-service-sidecar|account-lookup-service-admin-sidcar|centralledger-handler-admin-transfer-sidecar|centralledger-handler-timeout-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-fulfil-sidecar|centralledger-handler-transfer-get-sidecar|centralledger-handler-transfer-position-sidecar|centralledger-service-sidecar\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{container}}-{{id}}"
    }
   ]
  },
  {
   "title": "Database containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"mojaloop-db\", container=\"mysql\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Database container cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"mojaloop-db\", container=\"mysql\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Mojaloop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Mojaloop replicaset count",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"mojaloop\",deployment=~\".*(account-lookup-service|account-lookup-service-admin|centralledger-handler-admin-transfer|centralledger-handler-timeout|centralledger-handler-transfer-fulfil|centralledger-handler-transfer-get|centralledger-handler-transfer-position|centralledger-service).*\", cluster=\"$cluster\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "MySQL statefulset count",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 60 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_available{namespace=\"mojaloop-db\", statefulset=~\".*(mysql).*\", cluster=\"$cluster\"}) by (statefulset)",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Kafka statefulset count",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_available{namespace=\"mojaloop\", statefulset=~\".*(kafka).*\", cluster=\"$cluster\"}) by (statefulset)",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  { "title": "My SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by (pod)(mysql_global_status_max_used_connections{namespace=\"mojaloop-db\", cluster=\"$cluster\"})",
     "legendFormat": "Max Use Connections {{pod}}"
    },
    {
     "expr": "sum by (pod)(mysql_global_variables_max_connections{namespace=\"mojaloop-db\", cluster=\"$cluster\"})",
     "legendFormat": "Max Connections {{pod}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Partition count w-r-t topic",
   "type": "barchart",
   "description": "Shows the no. of partitions for each topic",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{cluster=\"$cluster\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumers count  w-r-t consumer group",
   "type": "barchart",
   "description": "Shows the no. of consumers in each consumer group",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{cluster=\"$cluster\"}) by (consumergroup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max consumer group lag",
   "type": "barchart",
   "description": "Shows the maximum lag (in message count) faced by a consumer in given (consumergroup,topic). ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "max(clamp_min(kafka_consumergroup_lag{cluster=\"$cluster\"},0)) by (consumergroup,topic)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}