{{- if and .Values.kps.grafana.enabled .Values.grafanaAdminSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promfana.grafanaAdminSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.grafanaAdminSecret.userKey }}: {{ .Values.grafanaAdminSecret.username | quote }}
  {{ .Values.grafanaAdminSecret.passwordKey }}: {{ .Values.grafanaAdminSecret.password | quote }}
{{- end }}
