{{- if .Values.gateway.enabled -}}
{{- $parentRefs := .Values.gateway.parentRefs -}}
{{- if .Values.gateway.hosts.hydra }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hydra-public
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.gateway.hosts.hydra | quote }}
  rules:
    - backendRefs:
        - name: ml-iam-hydra-public
          port: 4444
{{- end }}
{{- if .Values.gateway.hosts.kratos }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kratos-public
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.gateway.hosts.kratos | quote }}
  rules:
    - backendRefs:
        - name: kratos-public
          port: 80
{{- end }}
{{- if and .Values.gateway.hosts.auth .Values.kratosUI.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kratos-ui
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.gateway.hosts.auth | quote }}
  rules:
    - backendRefs:
        - name: ml-iam-kratosUI
          port: 80
{{- end }}
{{- if and .Values.gateway.hosts.mailpit .Values.mailpit.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mailpit
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.gateway.hosts.mailpit | quote }}
  rules:
    - backendRefs:
        - name: ml-iam-mailpit-http
          port: 80
{{- end }}
{{- if .Values.gateway.crossNamespaceMcmApi.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: mcm-api-to-oathkeeper-proxy
  namespace: {{ .Release.Namespace }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.gateway.crossNamespaceMcmApi.fromNamespace | quote }}
  to:
    - group: ""
      kind: Service
      name: oathkeeper-proxy
{{- end }}
{{- end }}
