{{- if not .Values.api.disabled -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: api
{{ include "connection-manager.labels" . | indent 4 }}

{{- end -}}
