{
 "title": "Kafka - Cluster Overview",
 "description": "A dashboard developed for kafka running on k8s using helm charts",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "Helm Release",
    "query": "label_values(kafka_log_log_logstartoffset, release)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_log_log_logstartoffset{release=\"$release\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "$topic topic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_log_logendoffset{release=\"$release\", topic=~\"$topic\"}) - sum(kafka_log_log_logstartoffset{release=\"$release\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages in: p/s  Topic: $topic",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_oneminuterate{release=\"$release\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(java_lang_runtime_uptime{release=\"$release\"})"
    }
   ]
  },
  {
   "title": "Topic BytesIn to BytesOut Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate{release=\"$release\", topic=~\"$topic\"})",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate{release=\"$release\", topic=~\"$topic\"})",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Network Processor Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kafka_network_processor_idlepercent_value{release=\"$release\"}",
     "legendFormat": " pod: {{ pod }} - processor: {{ network_processor }}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{release=\"$release\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM System CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{release=\"$release\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_partitioncount_value{release=\"$release\"})"
    }
   ]
  },
  {
   "title": "Total Under Replicated Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_underreplicatedpartitions_value{release=\"$release\"})"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "java_lang_runtime_uptime{release=\"$release\"}",
     "legendFormat": "Broker {{ pod }}"
    }
   ]
  },
  {
   "title": "Kafka Network Request Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (request) (irate (kafka_network_requestmetrics_requestspersec_count{release=\"$release\"}[1m]))",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Max lag in messages btw follower and leader replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag_value{release=\"$release\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Request Handler Idle (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{release=\"$release\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}